"""private messages language

Revision ID: ef226ac685cb
Revises: fdd9d4c520bd
Create Date: 2020-07-06 17:27:30.310390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef226ac685cb'
down_revision = 'fdd9d4c520bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'language')
    # ### end Alembic commands ###
